#! /bin/bash

#rm *.html <LIST ANY OTHER FILES>
rm *.html
#rm -r MoreFiles Assignments <LIST ANY OTHER FOLDERS>
rm -r MoreFiles Assignments
rm apache-helpers.zip
zip -r apache-helpers css/ js/ images/
